{% set version = "2.1.9" %}

package:
  name: bob.io.matlab
  version: {{ version }}

source:
  fn: bob.io.matlab-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.io.matlab/bob.io.matlab-{{ version }}.zip
  md5: d1c437d2154f0828f4be1690bb6a6690

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - libmatio 1.5.*
    - pkg-config
    - boost 1.61.*

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - libmatio 1.5.*
    - boost 1.61.*

test:
  imports:
    - bob
    - bob.io
    - bob.io.matlab
  commands:
    - nosetests -sv bob.io.matlab
  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Enable bob.io.base to handle Matlab(R) files

extra:
  recipe-maintainers:
    - 183amir
